name = "exam-countdown"
main = "src/index.js"
compatibility_date = "2023-05-18"

# Configure environment variables (update these with your real values)
[vars]
GOTIFY_URL = "https://your-gotify-server.example.com"
GOTIFY_TOKEN = "your-gotify-app-token"

# Configure cron triggers for notifications
[triggers]
crons = ["0 8 * * *", "0 18 * * *"] # 8 AM and 6 PM IST (in UTC)
