name = "exam-countdown"
main = "src/index.js"
compatibility_date = "2023-05-18"

# Configure environment variables (update these with your real values)
[vars]
GOTIFY_URL = "http://68.233.115.164:6940"
GOTIFY_TOKEN = "A9Y55xTVo1QZNUt"

# Configure cron triggers for notifications
[triggers]
crons = ["0 8 * * *", "0 18 * * *"] # 8 AM and 6 PM IST (in UTC)
